name: CI Pipeline

on:
  push:
    branches:
      - '**'  # Триггер сработает для всех веток
  pull_request:
    branches:
      - '**'  # Триггер сработает для всех веток

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_BOT_USERNAME: ${{ secrets.TELEGRAM_BOT_USERNAME }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'oracle'

      - name: Create .env file
        run: |
            echo "TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}" > .env
            echo "TELEGRAM_BOT_USERNAME=${{ secrets.TELEGRAM_BOT_USERNAME }}" >> .env

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2

      - name: Add gradle wrapper jar
        run: ./gradlew wrapper

      - name: Build with Gradle
        run: ./gradlew build

      - name: Test with Gradle
        run: ./gradlew test